[package]
name = "png-glitch-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
png-glitch = "0.5.0"

[package.metadata.component]
package = "reo0306:glitch-art"